export const IMAGES_LIST = [
    {
        images:"/assets/images/pet-two.webp"
    },
    {
        images:"/assets/images/pet-six.webp"
    },
    {
        images:"/assets/images/pet-three.webp"
    },
    {
        images:"/assets/images/pet-four.webp"
    },
    {
        images:"/assets/images/pet-five.webp"
    },
    {
        images:"/assets/images/pet-one.webp"
    },
];